/* CREATE TABLE */
CREATE TABLE IF NOT EXISTS PUBLICATIONS(
  PUBLICATION_HOUSE VARCHAR(100) NOT NULL, 
  ISBN INT NOT NULL , 
  PHONE_NO DECIMAL INT, 
  WEBSITE VARCHAR(100),
  PRIMARY KEY(PUBLICATION_HOUSE),
  FOREIGN KEY (ISBN) REFERENCES BOOKS(ISBN) ON DELETE CASCADE
);
/* INSERT QUERY */
INSERT INTO PUBLICATIONS(
  PUBLICATION_HOUSE, ISBN, PHONE_NO, 
  WEBSITE
) 
VALUES 
  (
    'INDIGO BOOKS 1', 180, 97959398, 
    'indigo.books.com'
  );
/* INSERT QUERY */
INSERT INTO PUBLICATIONS(
  PUBLICATION_HOUSE, ISBN, PHONE_NO, 
  WEBSITE
) 
VALUES 
  (
    'INDIGO BOOKS 2', 181, 97959391, 
    'indigo.books.com'
  );
/* INSERT QUERY */
INSERT INTO PUBLICATIONS(
  PUBLICATION_HOUSE, ISBN, PHONE_NO, 
  WEBSITE
) 
VALUES 
  (
    'ABACUS', 182, 97969594, 'abacus.publishinghouse.com'
  );
/* INSERT QUERY */
INSERT INTO PUBLICATIONS(
  PUBLICATION_HOUSE, ISBN, PHONE_NO, 
  WEBSITE
) 
VALUES 
  (
    'JAICO PUBLISHING HOUSE', 183, 
    87654321, 'jaicopublishinghouse.com'
  );
/* INSERT QUERY */
INSERT INTO PUBLICATIONS(
  PUBLICATION_HOUSE, ISBN, PHONE_NO, 
  WEBSITE
) 
VALUES 
  (
    'LEXICON BOOKS', 184, 88997700, 
    'lexicon.com'
  );
/* INSERT QUERY */
INSERT INTO PUBLICATIONS(
  PUBLICATION_HOUSE, ISBN, PHONE_NO, 
  WEBSITE
) 
VALUES 
  (
    'ARROW', 185, 66775588, 'arrow.eu'
  );
/* INSERT QUERY */
INSERT INTO PUBLICATIONS(
  PUBLICATION_HOUSE, ISBN, PHONE_NO, 
  WEBSITE
) 
VALUES 
  (
    'LADYBIRD', 186, 33554466, 'ladybirdpenguin.de'
  );
/* INSERT QUERY */
INSERT INTO PUBLICATIONS(
  PUBLICATION_HOUSE, ISBN, PHONE_NO, 
  WEBSITE
) 
VALUES 
  (
    'PENGUIN BOOKS 1', 187, 77990098, 
    'penguin.com'
  );
/* INSERT QUERY */
INSERT INTO PUBLICATIONS(
  PUBLICATION_HOUSE, ISBN, PHONE_NO, 
  WEBSITE
) 
VALUES 
  (
    'SCHOLASTIC INC.', 188, 98763210, 
    'scholasticbooks.com'
  );
/* INSERT QUERY */
INSERT INTO PUBLICATIONS(
  PUBLICATION_HOUSE, ISBN, PHONE_NO, 
  WEBSITE
) 
VALUES 
  (
    'PENGUIN BOOKS 2', 189, 77990099, 
    'penguin.com'
  );
